### ISSUE TITLE
cisco-spark-api-0.1.0.0 build failure with conduit-combinators-1.3.0

### ISSUE THREAD

**Issue by DanBurton** [nshimaza/cisco-spark-api#1]
As seen on the Stackage build server:

```
[3 of 3] Compiling Network.CiscoSpark ( src/Network/CiscoSpark.hs, dist/build/Network/CiscoSpark.o )

src/Network/CiscoSpark.hs:188:1: error:
    Could not find module ‘Conduit’
    Use -v to see a list of the files searched for.
    |
188 | import           Conduit
    | ^^^^^^^^^^^^^^^^^^^^^^^^
```

(Note that conduit-combinators is now an empty package, as its functionality I believe has moved into conduit itself.)

I was able to reproduce this build failure locally like so:

```bash
stack unpack cisco-spark-api-0.1.0.0 && cd cisco-spark-api-0.1.0.0
edit stack.yaml # add the following stack.yaml
stack build
```

```yaml
# stack.yaml
resolver: nightly-2018-03-10
extra-deps:
- conduit-combinators-1.3.0
```
